### ISSUE TITLE
Does not seem to work on Windows

### ISSUE THREAD

**Issue by jeancastellotti** [SoftwareCitadel/adonisjs-girouette#1]
Hi.

I wanted to give it a try today, but I'm getting this error. I'm using Windows 11 and node 20.16.0.

![image](https://github.com/user-attachments/assets/e806b33c-9d3a-491e-bb63-183c32fb97ea)

**Comment by alexisbouchez** [comment]
Thanks for reporting, will look into it.

**Comment by alexisbouchez** [comment]
Released as v0.0.6, thanks to this PR https://github.com/SoftwareCitadel/adonisjs-girouette/pull/2 from @kubilaysalih !

Thanks again for reporting, and to @kubilaysalih for implementing the fix.
